runChecks: true

actions:
  branch-protection-settings:
    branches:
      - name: main
        numRequiredReviews: 1
        requireBranchUpToDate: true
        requireConversationResolution: true
        requireLinearHistory: true
        checks:
          - name: minerva tests
            appId: github-actions
            type: tests
          - name: trufflehog credential leaks
            appId: github-actions
            type: tests

  repo-settings:
    deleteBranchOnMerge: true
 
