name: Run tests

on:
  pull_request:
  push:
    branches:
      - main
      - trunk

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  minerva_tests:
    name: "minerva tests"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Lint with flake8
        run: |
          python3 -m pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 ./minerva/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 ./minerva/ --count  --ignore=W504,W503,W605,E741,E226 --max-complexity=32 --max-line-length=127 --statistics
          # stop the build if there are Python syntax errors or undefined names
          flake8 ./tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 ./tests/ --count  --ignore=W504,W503,W605,E741,E226 --max-complexity=32 --max-line-length=127 --statistics

      - name: Installing minerva dependencies
        run: |
          python3 -m pip install --upgrade pip wheel setuptools virtualenv
          virtualenv minerva-env
          source minerva-env/bin/activate
          python3 -m pip install poetry
          python3 -m pip install pytest
          poetry lock
          poetry install

      - name: Run minerva tests
        run: |
          source minerva-env/bin/activate
          poetry run pytest tests/*_test.py --disable-warnings
