name: Run tests

on:
  pull_request:
  push:
    branches:
      - main
      - trunk

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  minerva_tests:
    name: "minerva tests"
    runs-on:
      - self-hosted
      - production
      - xlarge
    container: docker.tw.ee/actions_python3_9

    steps:
      # GHA leaves mess behind. We need to clear those or our we end up having unexpected behaviours.
      # REMOVE ME when A&T uses ephemeral runners
      - name: Clear dirty runner
        # Clear everything, both home and working directory
        run: |
          rm -rfv ~/* ./* || true

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installing minerva dependencies
        run: |
          virtualenv minerva-env
          source minerva-env/bin/activate
          python3 -m pip install --upgrade pip wheel setuptools
          python3 -m pip install poetry
          python3 -m pip install pytest
          poetry lock
          poetry install

      - name: Run minerva tests
        run: |
          source minerva-env/bin/activate
          poetry run pytest  --disable-warnings

  run_trufflehog:
    name: "Run trufflehog to catch credential leaks"
    runs-on:
      - self-hosted
      - production
      - medium
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug
